-- ============================================================
-- Egyptian market drugs & brands (manually curated)
-- Idempotent — safe to re-run.
--
-- NOTE: This is a starting catalogue. The real solution is EDA API
-- access (see docs/data-sources.md). Until then, expand this file
-- incrementally as needed.
-- ============================================================

-- -----------------------------------------------------------------
-- 1. Generic drugs (INN names, AR + EN)
-- -----------------------------------------------------------------
INSERT INTO drugs (rxcui, generic_en, generic_ar, drug_class) VALUES
  -- Analgesics / NSAIDs
  (NULL, 'Paracetamol',       'باراسيتامول',        'Analgesic'),
  (NULL, 'Ibuprofen',         'إيبوبروفين',         'NSAID'),
  (NULL, 'Diclofenac',        'ديكلوفيناك',         'NSAID'),
  (NULL, 'Naproxen',          'نابروكسين',          'NSAID'),
  (NULL, 'Mefenamic Acid',    'حمض الميفيناميك',    'NSAID'),
  (NULL, 'Aspirin',           'أسبرين',             'Antiplatelet'),
  (NULL, 'Ketoprofen',        'كيتوبروفين',         'NSAID'),
  (NULL, 'Piroxicam',         'بيروكسيكام',         'NSAID'),
  (NULL, 'Meloxicam',         'ميلوكسيكام',         'NSAID'),
  -- Antibiotics
  (NULL, 'Amoxicillin',       'أموكسيسيلين',        'Antibiotic'),
  (NULL, 'Amoxicillin/Clavulanate', 'أموكسيسيلين/كلافولانيت', 'Antibiotic'),
  (NULL, 'Azithromycin',      'أزيثرومايسين',       'Antibiotic'),
  (NULL, 'Ciprofloxacin',     'سيبروفلوكساسين',     'Antibiotic'),
  (NULL, 'Levofloxacin',      'ليفوفلوكساسين',      'Antibiotic'),
  (NULL, 'Clarithromycin',    'كلاريثروميسين',      'Antibiotic'),
  (NULL, 'Cefixime',          'سيفيكسيم',           'Antibiotic'),
  (NULL, 'Ceftriaxone',       'سيفترياكسون',        'Antibiotic'),
  (NULL, 'Cephalexin',        'سيفاليكسين',         'Antibiotic'),
  (NULL, 'Doxycycline',       'دوكسيسيكلين',        'Antibiotic'),
  (NULL, 'Metronidazole',     'ميترونيدازول',       'Antibiotic'),
  (NULL, 'Nitrofurantoin',    'نيتروفورانتوين',     'Antibiotic'),
  (NULL, 'Nifuroxazide',      'نيفوروكسازيد',       'Antibacterial'),
  (NULL, 'Trimethoprim/Sulfamethoxazole', 'تريميثوبريم/سلفاميثوكسازول', 'Antibiotic'),
  -- Cardiovascular
  (NULL, 'Amlodipine',        'أملوديبين',          'CCB'),
  (NULL, 'Nifedipine',        'نيفيديبين',          'CCB'),
  (NULL, 'Diltiazem',         'ديلتيازيم',          'CCB'),
  (NULL, 'Verapamil',         'فيراباميل',          'CCB'),
  (NULL, 'Bisoprolol',        'بيسوبرولول',         'Beta-blocker'),
  (NULL, 'Atenolol',          'أتينولول',           'Beta-blocker'),
  (NULL, 'Metoprolol',        'ميتوبرولول',         'Beta-blocker'),
  (NULL, 'Carvedilol',        'كارفيديلول',         'Beta-blocker'),
  (NULL, 'Lisinopril',        'ليزينوبريل',         'ACE inhibitor'),
  (NULL, 'Enalapril',         'إنالابريل',          'ACE inhibitor'),
  (NULL, 'Captopril',         'كابتوبريل',          'ACE inhibitor'),
  (NULL, 'Losartan',          'لوسارتان',           'ARB'),
  (NULL, 'Valsartan',         'فالسارتان',          'ARB'),
  (NULL, 'Candesartan',       'كانديسارتان',        'ARB'),
  (NULL, 'Hydrochlorothiazide','هيدروكلوروثيازيد',  'Diuretic'),
  (NULL, 'Furosemide',        'فوروسيميد',          'Diuretic'),
  (NULL, 'Spironolactone',    'سبيرونولاكتون',      'Diuretic'),
  (NULL, 'Atorvastatin',      'أتورفاستاتين',       'Statin'),
  (NULL, 'Rosuvastatin',      'روسوفاستاتين',       'Statin'),
  (NULL, 'Simvastatin',       'سيمفاستاتين',        'Statin'),
  (NULL, 'Clopidogrel',       'كلوبيدوجريل',        'Antiplatelet'),
  (NULL, 'Warfarin',          'وارفارين',           'Anticoagulant'),
  (NULL, 'Rivaroxaban',       'ريفاروكسابان',       'Anticoagulant'),
  (NULL, 'Apixaban',          'أبيكسابان',          'Anticoagulant'),
  (NULL, 'Digoxin',           'ديجوكسين',           'Cardiac glycoside'),
  (NULL, 'Nitroglycerin',     'نيتروجليسرين',       'Nitrate'),
  (NULL, 'Isosorbide Mononitrate', 'أيزوسوربيد مونونيترات', 'Nitrate'),
  -- Diabetes
  (NULL, 'Metformin',         'ميتفورمين',          'Antidiabetic'),
  (NULL, 'Gliclazide',        'جليكلازيد',          'Antidiabetic'),
  (NULL, 'Glimepiride',       'جليميبيريد',         'Antidiabetic'),
  (NULL, 'Sitagliptin',       'سيتاجليبتين',        'Antidiabetic'),
  (NULL, 'Insulin Glargine',  'إنسولين جلارجين',    'Antidiabetic'),
  (NULL, 'Empagliflozin',     'إمباجليفلوزين',      'Antidiabetic'),
  -- GI
  (NULL, 'Omeprazole',        'أوميبرازول',         'PPI'),
  (NULL, 'Esomeprazole',      'إيزوميبرازول',       'PPI'),
  (NULL, 'Pantoprazole',      'بانتوبرازول',        'PPI'),
  (NULL, 'Ranitidine',        'رانيتيدين',          'H2 blocker'),
  (NULL, 'Famotidine',        'فاموتيدين',          'H2 blocker'),
  (NULL, 'Domperidone',       'دومبيريدون',         'Antiemetic'),
  (NULL, 'Metoclopramide',    'ميتوكلوبراميد',      'Antiemetic'),
  (NULL, 'Ondansetron',       'أوندانسيترون',       'Antiemetic'),
  (NULL, 'Hyoscine Butylbromide', 'هيوسين بوتيل بروميد', 'Antispasmodic'),
  (NULL, 'Loperamide',        'لوبيراميد',          'Antidiarrheal'),
  (NULL, 'Lactulose',         'لاكتولوز',           'Laxative'),
  (NULL, 'Bisacodyl',         'بيساكوديل',          'Laxative'),
  -- Respiratory / Allergy
  (NULL, 'Salbutamol',        'سالبوتامول',         'Bronchodilator'),
  (NULL, 'Budesonide/Formoterol', 'بوديسونيد/فورموتيرول', 'Bronchodilator'),
  (NULL, 'Montelukast',       'مونتيلوكاست',        'Leukotriene inhibitor'),
  (NULL, 'Cetirizine',        'سيتريزين',           'Antihistamine'),
  (NULL, 'Loratadine',        'لوراتادين',          'Antihistamine'),
  (NULL, 'Fexofenadine',      'فيكسوفينادين',       'Antihistamine'),
  (NULL, 'Chlorpheniramine',  'كلورفينيرامين',      'Antihistamine'),
  (NULL, 'Desloratadine',     'ديسلوراتادين',       'Antihistamine'),
  -- Thyroid / Hormones
  (NULL, 'Levothyroxine',     'ليفوثيروكسين',       'Thyroid hormone'),
  (NULL, 'Carbimazole',       'كاربيمازول',         'Antithyroid'),
  (NULL, 'Prednisolone',      'بريدنيزولون',        'Corticosteroid'),
  (NULL, 'Dexamethasone',     'ديكساميثازون',       'Corticosteroid'),
  (NULL, 'Hydrocortisone',    'هيدروكورتيزون',      'Corticosteroid'),
  -- CNS / Psychiatry
  (NULL, 'Sertraline',        'سيرترالين',          'SSRI'),
  (NULL, 'Fluoxetine',        'فلوكستين',           'SSRI'),
  (NULL, 'Escitalopram',      'إسيتالوبرام',        'SSRI'),
  (NULL, 'Alprazolam',        'ألبرازولام',         'Benzodiazepine'),
  (NULL, 'Diazepam',          'ديازيبام',           'Benzodiazepine'),
  (NULL, 'Gabapentin',        'جابابنتين',          'Anticonvulsant'),
  (NULL, 'Pregabalin',        'بريجابالين',         'Anticonvulsant'),
  (NULL, 'Carbamazepine',     'كاربامازيبين',       'Anticonvulsant'),
  (NULL, 'Valproic Acid',     'حمض الفالبرويك',     'Anticonvulsant'),
  (NULL, 'Sumatriptan',       'سوماتريبتان',        'Antimigraine'),
  -- Musculoskeletal
  (NULL, 'Allopurinol',       'ألوبيورينول',        'Antigout'),
  (NULL, 'Colchicine',        'كولشيسين',           'Antigout'),
  (NULL, 'Febuxostat',        'فيبوكسوستات',        'Antigout'),
  (NULL, 'Methotrexate',      'ميثوتريكسات',        'DMARD'),
  -- Ophthalmology / Dermatology
  (NULL, 'Timolol',           'تيمولول',            'Beta-blocker (ophthalmic)'),
  (NULL, 'Latanoprost',       'لاتانوبروست',        'Prostaglandin (ophthalmic)'),
  (NULL, 'Moxifloxacin',      'موكسيفلوكساسين',     'Antibiotic (ophthalmic)'),
  (NULL, 'Mupirocin',         'موبيروسين',          'Antibiotic (topical)'),
  (NULL, 'Clotrimazole',      'كلوتريمازول',        'Antifungal'),
  (NULL, 'Fluconazole',       'فلوكونازول',         'Antifungal'),
  (NULL, 'Terbinafine',       'تيربينافين',         'Antifungal'),
  (NULL, 'Acyclovir',         'أسيكلوفير',          'Antiviral')
ON CONFLICT (rxcui) DO NOTHING;

-- -----------------------------------------------------------------
-- 2. Egyptian market brands
-- -----------------------------------------------------------------
INSERT INTO products (drug_id, brand_en, brand_ar, market, manufacturer,
                     registration_no, form, strength, source)
SELECT d.id, v.brand_en, v.brand_ar, 'EG', v.manufacturer,
       v.reg_no, v.form, v.strength, 'EDA'
FROM (VALUES
    -- Analgesics
    ('Paracetamol',       'Panadol',      'بنادول',           'GSK',              'EDA-PANADOL-500',    'Tablet',  '500mg'),
    ('Paracetamol',       'Adol',         'أدول',             'Julphar',          'EDA-ADOL-500',       'Tablet',  '500mg'),
    ('Paracetamol',       'Panadol Extra','بنادول إكسترا',    'GSK',              'EDA-PANADOL-EX-500', 'Tablet',  '500mg+caffeine'),
    ('Paracetamol',       'Cetal',        'سيتال',            'Amriya',           'EDA-CETAL-500',      'Tablet',  '500mg'),
    ('Ibuprofen',         'Brufen',       'بروفين',           'Abbott',           'EDA-BRUFEN-400',     'Tablet',  '400mg'),
    ('Ibuprofen',         'Brufen 600',   'بروفين ٦٠٠',       'Abbott',           'EDA-BRUFEN-600',     'Tablet',  '600mg'),
    ('Diclofenac',        'Cataflam',     'كاتافلام',         'Novartis',         'EDA-CATAFLAM-50',    'Tablet',  '50mg'),
    ('Diclofenac',        'Voltaren',     'فولتارين',         'Novartis',         'EDA-VOLTAREN-75',    'Tablet',  '75mg'),
    ('Diclofenac',        'Voltaren Gel', 'فولتارين جيل',     'Novartis',         'EDA-VOLTAREN-GEL',   'Gel',     '1%'),
    ('Naproxen',          'Anaprox',      'أنابروكس',         'Roche',            'EDA-ANAPROX-275',    'Tablet',  '275mg'),
    ('Mefenamic Acid',    'Ponstan',      'بونستان',          'Pfizer',           'EDA-PONSTAN-500',    'Tablet',  '500mg'),
    ('Aspirin',           'Aspocid',      'أسبوسيد',          'CID',              'EDA-ASPOCID-75',     'Tablet',  '75mg'),
    ('Aspirin',           'Aspirin Protect','أسبرين بروتكت',  'Bayer',            'EDA-ASPIRIN-100',    'Tablet',  '100mg'),
    ('Ketoprofen',        'Ketofan',      'كيتوفان',          'Amriya',           'EDA-KETOFAN-100',    'Tablet',  '100mg'),
    ('Piroxicam',         'Feldene',      'فيلدين',           'Pfizer',           'EDA-FELDENE-20',     'Capsule', '20mg'),
    ('Meloxicam',         'Mobic',        'موبيك',            'Boehringer',       'EDA-MOBIC-15',       'Tablet',  '15mg'),
    -- Antibiotics
    ('Amoxicillin',       'Amoxil',       'أموكسيل',          'GSK',              'EDA-AMOXIL-500',     'Capsule', '500mg'),
    ('Amoxicillin',       'Hibiotic',     'هايبيوتك',         'Hikma',            'EDA-HIBIOTIC-500',   'Capsule', '500mg'),
    ('Amoxicillin/Clavulanate', 'Augmentin', 'أوجمنتين',      'GSK',              'EDA-AUGMENTIN-1G',   'Tablet',  '1g'),
    ('Amoxicillin/Clavulanate', 'Hibiotic Plus', 'هايبيوتك بلس', 'Hikma',         'EDA-HIBIOTIC-PLUS',  'Tablet',  '1g'),
    ('Azithromycin',      'Zithromax',    'زيثروماكس',        'Pfizer',           'EDA-ZITHROMAX-500',  'Tablet',  '500mg'),
    ('Azithromycin',      'Zithromax Susp', 'زيثروماكس شراب', 'Pfizer',           'EDA-ZITHROMAX-SUSP', 'Suspension', '200mg/5ml'),
    ('Ciprofloxacin',     'Ciprofar',     'سيبروفار',         'Pharco',           'EDA-CIPROFAR-500',   'Tablet',  '500mg'),
    ('Ciprofloxacin',     'Ciprobay',     'سيبروباي',         'Bayer',            'EDA-CIPROBAY-500',   'Tablet',  '500mg'),
    ('Levofloxacin',      'Tavanic',      'تافانيك',          'Sanofi',           'EDA-TAVANIC-500',    'Tablet',  '500mg'),
    ('Clarithromycin',    'Klacid',       'كلاسيد',           'Abbott',           'EDA-KLACID-500',     'Tablet',  '500mg'),
    ('Cefixime',          'Suprax',       'سوبراكس',          'Sanofi',           'EDA-SUPRAX-400',     'Tablet',  '400mg'),
    ('Ceftriaxone',       'Rocephin',     'روسيڤين',          'Roche',            'EDA-ROCEPHIN-1G',    'Injection','1g'),
    ('Cephalexin',        'Keflex',       'كيفلكس',           'Lilly',            'EDA-KEFLEX-500',     'Capsule', '500mg'),
    ('Doxycycline',       'Vibramycin',   'فيبراميسين',       'Pfizer',           'EDA-VIBRAMYCIN-100', 'Capsule', '100mg'),
    ('Metronidazole',     'Flagyl',       'فلاجيل',           'Sanofi',           'EDA-FLAGYL-500',     'Tablet',  '500mg'),
    ('Nitrofurantoin',    'Macrobid',     'ماكروبيد',         'Procter',          'EDA-MACROBID-100',   'Capsule', '100mg'),
    ('Nifuroxazide',      'Antinal',      'أنتينال',          'Amoun',            'EDA-ANTINAL-200',    'Capsule', '200mg'),
    ('Trimethoprim/Sulfamethoxazole','Bactrim','باكترم',     'Roche',            'EDA-BACTRIM-960',    'Tablet',  '960mg'),
    -- Cardiovascular
    ('Amlodipine',        'Norvasc',      'نورفاسك',          'Pfizer',           'EDA-NORVASC-5',      'Tablet',  '5mg'),
    ('Amlodipine',        'Amlor',        'أملور',            'Pfizer',           'EDA-AMLOR-5',        'Tablet',  '5mg'),
    ('Amlodipine',        'Amlopin',      'أملوبين',          'Amoun',            'EDA-AMLOPIN-5',      'Tablet',  '5mg'),
    ('Nifedipine',        'Adalat',       'أدالات',           'Bayer',            'EDA-ADALAT-30',      'Tablet',  '30mg'),
    ('Bisoprolol',        'Concor',       'كونكور',           'Merck',            'EDA-CONCOR-5',       'Tablet',  '5mg'),
    ('Atenolol',          'Tenormin',     'تينورمين',         'AstraZeneca',      'EDA-TENORMIN-50',    'Tablet',  '50mg'),
    ('Metoprolol',        'Betaloc',      'بيتالوك',          'AstraZeneca',      'EDA-BETALOC-100',    'Tablet',  '100mg'),
    ('Carvedilol',        'Dilatrend',    'ديلاترند',         'Roche',            'EDA-DILATREND-25',   'Tablet',  '25mg'),
    ('Lisinopril',        'Zestril',      'زيستريل',          'AstraZeneca',      'EDA-ZESTRIL-10',     'Tablet',  '10mg'),
    ('Enalapril',         'Renitec',      'رينيتيك',          'MSD',              'EDA-RENITEC-10',     'Tablet',  '10mg'),
    ('Captopril',         'Capoten',      'كابوتين',          'BMS',              'EDA-CAPOTEN-25',     'Tablet',  '25mg'),
    ('Losartan',          'Cozaar',       'كوزار',            'MSD',              'EDA-COZAAR-50',      'Tablet',  '50mg'),
    ('Valsartan',         'Diovan',       'ديوفان',           'Novartis',         'EDA-DIOVAN-80',      'Tablet',  '80mg'),
    ('Candesartan',       'Atacand',      'أتاكاند',          'AstraZeneca',      'EDA-ATACAND-8',      'Tablet',  '8mg'),
    ('Hydrochlorothiazide','Esidrex',     'إيزيدريكس',        'Novartis',         'EDA-ESIDREX-25',     'Tablet',  '25mg'),
    ('Furosemide',        'Lasix',        'لازيكس',           'Sanofi',           'EDA-LASIX-40',       'Tablet',  '40mg'),
    ('Spironolactone',    'Aldactone',    'ألداكتون',         'Pfizer',           'EDA-ALDACTONE-25',   'Tablet',  '25mg'),
    ('Atorvastatin',      'Lipitor',      'ليبيتور',          'Pfizer',           'EDA-LIPITOR-20',     'Tablet',  '20mg'),
    ('Atorvastatin',      'Ator',         'أتور',             'Hikma',            'EDA-ATOR-20',        'Tablet',  '20mg'),
    ('Rosuvastatin',      'Crestor',      'كريستور',          'AstraZeneca',      'EDA-CRESTOR-10',     'Tablet',  '10mg'),
    ('Simvastatin',       'Zocor',        'زوكور',            'MSD',              'EDA-ZOCOR-20',       'Tablet',  '20mg'),
    ('Clopidogrel',       'Plavix',       'بلافيكس',          'Sanofi',           'EDA-PLAVIX-75',      'Tablet',  '75mg'),
    ('Clopidogrel',       'Clopidix',     'كلوبيدكس',         'Amriya',           'EDA-CLOPIDIX-75',    'Tablet',  '75mg'),
    ('Warfarin',          'Marevan',      'ماريفان',          'Aspen',            'EDA-MAREVAN-5',      'Tablet',  '5mg'),
    ('Rivaroxaban',       'Xarelto',      'زاريلتو',          'Bayer',            'EDA-XARELTO-20',     'Tablet',  '20mg'),
    ('Apixaban',          'Eliquis',      'إليكويس',          'BMS',              'EDA-ELIQUIS-5',      'Tablet',  '5mg'),
    ('Digoxin',           'Lanoxin',      'لانوكسين',         'GSK',              'EDA-LANOXIN-0.25',   'Tablet',  '0.25mg'),
    ('Nitroglycerin',     'Nitromint',    'نيترومينت',        'Egytp',            'EDA-NITROMINT-2.6',  'Tablet',  '2.6mg'),
    -- Diabetes
    ('Metformin',         'Cidophage',    'سيدوفاج',          'CID',              'EDA-CIDOPHAGE-500',  'Tablet',  '500mg'),
    ('Metformin',         'Glucophage',   'جلوكوفاج',         'Merck',            'EDA-GLUCOPHAGE-1G',  'Tablet',  '1g'),
    ('Metformin',         'Glucophage XR','جلوكوفاج XR',      'Merck',            'EDA-GLUCOPHAGE-XR',  'Tablet',  '500mg'),
    ('Gliclazide',        'Diamicron',    'دياميكرون',        'Servier',          'EDA-DIAMICRON-80',   'Tablet',  '80mg'),
    ('Gliclazide',        'Diamicron MR', 'دياميكرون MR',     'Servier',          'EDA-DIAMICRON-MR-30','Tablet',  '30mg'),
    ('Glimepiride',       'Amaryl',       'أماريل',           'Sanofi',           'EDA-AMARYL-2',       'Tablet',  '2mg'),
    ('Sitagliptin',       'Januvia',      'جانوفيا',          'MSD',              'EDA-JANUVIA-100',    'Tablet',  '100mg'),
    ('Insulin Glargine',  'Lantus',       'لانتوس',           'Sanofi',           'EDA-LANTUS-100',     'Injection','100U/ml'),
    ('Empagliflozin',     'Jardiance',    'جارديانس',         'Boehringer',       'EDA-JARDIANCE-10',   'Tablet',  '10mg'),
    -- GI
    ('Omeprazole',        'Losec',        'لوسيك',            'AstraZeneca',      'EDA-LOSEC-20',       'Capsule', '20mg'),
    ('Esomeprazole',      'Nexium',       'نيكسيوم',          'AstraZeneca',      'EDA-NEXIUM-40',      'Tablet',  '40mg'),
    ('Pantoprazole',      'Controloc',    'كنترولوك',         'Takeda',           'EDA-CONTROLOC-40',   'Tablet',  '40mg'),
    ('Ranitidine',        'Zantac',       'زانتاك',           'GSK',              'EDA-ZANTAC-150',     'Tablet',  '150mg'),
    ('Famotidine',        'Antodine',     'أنتودين',          'Amriya',           'EDA-ANTODINE-20',    'Tablet',  '20mg'),
    ('Domperidone',       'Motilium',     'موتيليوم',         'Janssen',          'EDA-MOTILIUM-10',    'Tablet',  '10mg'),
    ('Metoclopramide',    'Primperan',    'بريمبران',         'Sanofi',           'EDA-PRIMPERAN-10',   'Tablet',  '10mg'),
    ('Ondansetron',       'Zofran',       'زوفران',           'GSK',              'EDA-ZOFRAN-4',       'Tablet',  '4mg'),
    ('Hyoscine Butylbromide','Buscopan',  'بوسكوبان',         'Boehringer',       'EDA-BUSCOPAN-10',    'Tablet',  '10mg'),
    ('Loperamide',        'Imodium',      'إيموديوم',         'Janssen',          'EDA-IMODIUM-2',      'Capsule', '2mg'),
    ('Lactulose',         'Duphalac',     'دوفالاك',          'Abbott',           'EDA-DUPHALAC-10',    'Syrup',   '10g/15ml'),
    ('Bisacodyl',         'Dulcolax',     'دولكولاكس',        'Boehringer',       'EDA-DULCOLAX-5',     'Tablet',  '5mg'),
    -- Respiratory / Allergy
    ('Salbutamol',        'Ventolin',     'فنتولين',          'GSK',              'EDA-VENTOLIN-INH',   'Inhaler', '100mcg'),
    ('Salbutamol',        'Ventolin Neb','فنتولين نيبولايزر', 'GSK',              'EDA-VENTOLIN-NEB',   'Nebulizer','5mg/ml'),
    ('Budesonide/Formoterol','Symbicort', 'سيمبيكورت',        'AstraZeneca',      'EDA-SYMBICORT-160',  'Inhaler', '160/4.5'),
    ('Montelukast',       'Singulair',    'سنغولير',          'MSD',              'EDA-SINGULAIR-10',   'Tablet',  '10mg'),
    ('Cetirizine',        'Zyrtec',       'زيرتك',            'UCB',              'EDA-ZYRTEC-10',      'Tablet',  '10mg'),
    ('Loratadine',        'Claritine',    'كلاريتين',         'Bayer',            'EDA-CLARITINE-10',   'Tablet',  '10mg'),
    ('Fexofenadine',      'Telfast',      'تلفاست',           'Sanofi',           'EDA-TELFAST-180',    'Tablet',  '180mg'),
    ('Chlorpheniramine',  'Allergyl',     'أليرجيل',          'Amriya',           'EDA-ALLERGYL-4',     'Tablet',  '4mg'),
    ('Desloratadine',     'Aerius',       'إيريوس',           'MSD',              'EDA-AERIUS-5',       'Tablet',  '5mg'),
    -- Thyroid / Hormones
    ('Levothyroxine',     'Eltroxin',     'إلتروكسين',        'Aspen',            'EDA-ELTROXIN-50',    'Tablet',  '50mcg'),
    ('Levothyroxine',     'Euthyrox',     'إيوثيروكس',        'Merck',            'EDA-EUTHYROX-50',    'Tablet',  '50mcg'),
    ('Carbimazole',       'Neo-Mercazole','نيو-ميركازول',     'Amriya',           'EDA-NEOMERCAZOLE-5', 'Tablet',  '5mg'),
    ('Prednisolone',      'Hostacortin',  'هوستاكورتون',      'Sanofi',           'EDA-HOSTACORTIN-5',  'Tablet',  '5mg'),
    ('Dexamethasone',     'Dexasone',     'ديكسازون',         'Amriya',           'EDA-DEXASONE-0.5',   'Tablet',  '0.5mg'),
    -- CNS / Psychiatry
    ('Sertraline',        'Zoloft',       'زولوفت',           'Pfizer',           'EDA-ZOLOFT-50',      'Tablet',  '50mg'),
    ('Fluoxetine',        'Prozac',       'بروزاك',           'Lilly',            'EDA-PROZAC-20',      'Capsule', '20mg'),
    ('Escitalopram',      'Cipralex',     'سيبرالكس',         'Lundbeck',         'EDA-CIPRALEX-10',    'Tablet',  '10mg'),
    ('Alprazolam',        'Xanax',        'زاناكس',           'Pfizer',           'EDA-XANAX-0.5',      'Tablet',  '0.5mg'),
    ('Diazepam',          'Valium',       'فاليوم',           'Roche',            'EDA-VALIUM-5',       'Tablet',  '5mg'),
    ('Gabapentin',        'Neurontin',    'نيورونتين',        'Pfizer',           'EDA-NEURONTIN-300',  'Capsule', '300mg'),
    ('Pregabalin',        'Lyrica',       'ليريكا',           'Pfizer',           'EDA-LYRICA-75',      'Capsule', '75mg'),
    ('Carbamazepine',     'Tegretol',     'تيجريتول',         'Novartis',         'EDA-TEGRETOL-200',   'Tablet',  '200mg'),
    ('Valproic Acid',     'Depakine',     'ديباكين',          'Sanofi',           'EDA-DEPAKINE-500',   'Tablet',  '500mg'),
    ('Sumatriptan',       'Imigran',      'إيميجران',         'GSK',              'EDA-IMIGRAN-50',     'Tablet',  '50mg'),
    -- Musculoskeletal
    ('Allopurinol',       'Zyloric',      'زايلوريك',         'GSK',              'EDA-ZYLORIC-300',    'Tablet',  '300mg'),
    ('Colchicine',        'Colcrys',      'كولكريس',          'Takeda',           'EDA-COLCRYS-0.6',    'Tablet',  '0.6mg'),
    ('Febuxostat',        'Feburic',      'فيبوريك',          'Sanofi',           'EDA-FEBURIC-80',     'Tablet',  '80mg'),
    -- Dermatology / Antifungals
    ('Clotrimazole',      'Canesten',     'كانستن',           'Bayer',            'EDA-CANESTEN-CRM',   'Cream',   '1%'),
    ('Fluconazole',       'Diflucan',     'ديفلوكان',         'Pfizer',           'EDA-DIFLUCAN-150',   'Capsule', '150mg'),
    ('Terbinafine',       'Lamisil',      'لاميزيل',          'Novartis',         'EDA-LAMISIL-250',    'Tablet',  '250mg'),
    ('Acyclovir',         'Zovirax',      'زوفيراكس',         'GSK',              'EDA-ZOVIRAX-400',    'Tablet',  '400mg'),
    ('Mupirocin',         'Bactroban',    'باكتروبان',        'GSK',              'EDA-BACTROBAN-CRM',  'Cream',   '2%')
) AS v(generic, brand_en, brand_ar, manufacturer, reg_no, form, strength)
JOIN drugs d ON d.generic_en = v.generic
ON CONFLICT (market, registration_no) DO NOTHING;